name: Build and Release AMAI Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name AMAI-Installer --icon=icon.ico main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AMAI-Installer
        path: dist/AMAI-Installer.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: AMAI-Installer
        path: dist

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        files: dist/AMAI-Installer.exe
